### ISSUE TITLE
Support all other documented transaction emails

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#1065]
https://docs.google.com/document/d/1xJDpcJDKAlEtEw2KReUZs4DJutk3hiOJuXtFOk-nlu0/edit, this work includes everything except for activation/reactivation emails send out in bulk (see #1023 )

**Comment by lucasrmp-cb** [comment]
This issue scopes all the transaction emails not under the "Onboarding" category, that's because the backfill (reactivation email) will be done in another issue and all others were part of the initial launch

**Comment by lucasrmp-cb** [comment]
## TODO

### Templates

- [ ] Post action confirmation (NFT sent)
- [ ] Post action confirmation (pending NFT)
- [ ] Register to vote
- [ ] Follow on X
- [ ] Contact your Representative


### Logic

- [ ] Add trigger for additional reminders in the initial signup inngest function
- [ ] Add inngest function for post action confirmation
- [ ] Add trigger for post action confirmation

**Comment by lucasrmp-cb** [comment]
Deployed the additional initial signup reminders
