### ISSUE TITLE
Support transactional emails and send drip email campaign post-signup encouraging additional actions

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#640]
This task includes:
- setting up communication.standwithcrypto.org in sendgrid
- Adding a sendgrid webhook that sends events to mixpanel (edge function prob makes the most sense)
- setup react email
- setup unsubscribe flow
- Add the actual product email post-signup as an inngest flow
   - poll every 5 minutes to see if it's been at least 5 min since the user did the last action on the website, send an email after it's been five
   - multi day drip email follow up (design to spec). Check unsubscribe status and current state of user before sending every time
   - We'll need UX for new signups, and tweaked UX for triggering this flow for users who signed up a while ago and havent recieved communication ("We've launched accounts!")
 - a new "UserCommuncationJourney" model that has a datetimeCreated and a "journeyEnum" that will just have "INITIAL_SIGNUP" for now. 
 - A script we can run to send the initial journey  campaign to users programmatically. This script should query for users that dont have the  UserCommuncationJourney type yet and start the inngest flow. It should have a configurable limit of users to send to so we can roll out this flow gradually

**Comment by travisbloom-cb** [comment]
https://www.figma.com/design/MWzmEAYQC1NYZiD4BG0FlI/V2-Fast-Follows?node-id=3604-2389&t=DU7FEgenDMQCf7ym-0

**Comment by lucasrmp-cb** [comment]
Unsubscribe flow involves tracking in the db and mixpanel

**Comment by lucasrmp-cb** [comment]
## TODO

- [x] DB Schema changes
- [x] main Inngest function
- [ ] Webhook and event tracking
- [ ] Backfill script
- [ ] Check unsubscribe flow events
- [ ] identity / DNS config

**Comment by lucasrmp-cb** [comment]
We decided to include the other steps of the Initial Signup journey in this issue's scope, so this are the new templates to be implemented (see [this](https://docs.google.com/document/d/1xJDpcJDKAlEtEw2KReUZs4DJutk3hiOJuXtFOk-nlu0/edit) for more info):

- [ ] Finish your profile reminder
- [ ] Phone number reminder
- [ ] Membership reminder

**Comment by lucasrmp-cb** [comment]
### Bug Bash
https://docs.google.com/document/d/1c7RwcwOtMUHaYk4zfwnrO58Fot2pl18cxl2HLDX3NnY/edit
